// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: collections_service.proto

// Protobuf Java Version: 3.25.4
package io.qdrant.client.grpc;

public final class CollectionsService {
  private CollectionsService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031collections_service.proto\022\006qdrant\032\021col" +
      "lections.proto2\342\010\n\013Collections\022L\n\003Get\022 ." +
      "qdrant.GetCollectionInfoRequest\032!.qdrant" +
      ".GetCollectionInfoResponse\"\000\022I\n\004List\022\036.q" +
      "drant.ListCollectionsRequest\032\037.qdrant.Li" +
      "stCollectionsResponse\"\000\022I\n\006Create\022\030.qdra" +
      "nt.CreateCollection\032#.qdrant.CollectionO" +
      "perationResponse\"\000\022I\n\006Update\022\030.qdrant.Up" +
      "dateCollection\032#.qdrant.CollectionOperat" +
      "ionResponse\"\000\022I\n\006Delete\022\030.qdrant.DeleteC" +
      "ollection\032#.qdrant.CollectionOperationRe" +
      "sponse\"\000\022M\n\rUpdateAliases\022\025.qdrant.Chang" +
      "eAliases\032#.qdrant.CollectionOperationRes" +
      "ponse\"\000\022\\\n\025ListCollectionAliases\022$.qdran" +
      "t.ListCollectionAliasesRequest\032\033.qdrant." +
      "ListAliasesResponse\"\000\022H\n\013ListAliases\022\032.q" +
      "drant.ListAliasesRequest\032\033.qdrant.ListAl" +
      "iasesResponse\"\000\022f\n\025CollectionClusterInfo" +
      "\022$.qdrant.CollectionClusterInfoRequest\032%" +
      ".qdrant.CollectionClusterInfoResponse\"\000\022" +
      "W\n\020CollectionExists\022\037.qdrant.CollectionE" +
      "xistsRequest\032 .qdrant.CollectionExistsRe" +
      "sponse\"\000\022{\n\034UpdateCollectionClusterSetup" +
      "\022+.qdrant.UpdateCollectionClusterSetupRe" +
      "quest\032,.qdrant.UpdateCollectionClusterSe" +
      "tupResponse\"\000\022Q\n\016CreateShardKey\022\035.qdrant" +
      ".CreateShardKeyRequest\032\036.qdrant.CreateSh" +
      "ardKeyResponse\"\000\022Q\n\016DeleteShardKey\022\035.qdr" +
      "ant.DeleteShardKeyRequest\032\036.qdrant.Delet" +
      "eShardKeyResponse\"\000B,\n\025io.qdrant.client." +
      "grpc\252\002\022Qdrant.Client.Grpcb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.qdrant.client.grpc.Collections.getDescriptor(),
        });
    io.qdrant.client.grpc.Collections.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
