// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: points_service.proto

// Protobuf Java Version: 3.25.4
package io.qdrant.client.grpc;

public final class PointsService {
  private PointsService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024points_service.proto\022\006qdrant\032\014points.p" +
      "roto2\375\017\n\006Points\022A\n\006Upsert\022\024.qdrant.Upser" +
      "tPoints\032\037.qdrant.PointsOperationResponse" +
      "\"\000\022A\n\006Delete\022\024.qdrant.DeletePoints\032\037.qdr" +
      "ant.PointsOperationResponse\"\000\022/\n\003Get\022\021.q" +
      "drant.GetPoints\032\023.qdrant.GetResponse\"\000\022N" +
      "\n\rUpdateVectors\022\032.qdrant.UpdatePointVect" +
      "ors\032\037.qdrant.PointsOperationResponse\"\000\022N" +
      "\n\rDeleteVectors\022\032.qdrant.DeletePointVect" +
      "ors\032\037.qdrant.PointsOperationResponse\"\000\022I" +
      "\n\nSetPayload\022\030.qdrant.SetPayloadPoints\032\037" +
      ".qdrant.PointsOperationResponse\"\000\022O\n\020Ove" +
      "rwritePayload\022\030.qdrant.SetPayloadPoints\032" +
      "\037.qdrant.PointsOperationResponse\"\000\022O\n\rDe" +
      "letePayload\022\033.qdrant.DeletePayloadPoints" +
      "\032\037.qdrant.PointsOperationResponse\"\000\022M\n\014C" +
      "learPayload\022\032.qdrant.ClearPayloadPoints\032" +
      "\037.qdrant.PointsOperationResponse\"\000\022Y\n\020Cr" +
      "eateFieldIndex\022\".qdrant.CreateFieldIndex" +
      "Collection\032\037.qdrant.PointsOperationRespo" +
      "nse\"\000\022Y\n\020DeleteFieldIndex\022\".qdrant.Delet" +
      "eFieldIndexCollection\032\037.qdrant.PointsOpe" +
      "rationResponse\"\000\0228\n\006Search\022\024.qdrant.Sear" +
      "chPoints\032\026.qdrant.SearchResponse\"\000\022G\n\013Se" +
      "archBatch\022\031.qdrant.SearchBatchPoints\032\033.q" +
      "drant.SearchBatchResponse\"\000\022I\n\014SearchGro" +
      "ups\022\031.qdrant.SearchPointGroups\032\034.qdrant." +
      "SearchGroupsResponse\"\000\0228\n\006Scroll\022\024.qdran" +
      "t.ScrollPoints\032\026.qdrant.ScrollResponse\"\000" +
      "\022A\n\tRecommend\022\027.qdrant.RecommendPoints\032\031" +
      ".qdrant.RecommendResponse\"\000\022P\n\016Recommend" +
      "Batch\022\034.qdrant.RecommendBatchPoints\032\036.qd" +
      "rant.RecommendBatchResponse\"\000\022R\n\017Recomme" +
      "ndGroups\022\034.qdrant.RecommendPointGroups\032\037" +
      ".qdrant.RecommendGroupsResponse\"\000\022>\n\010Dis" +
      "cover\022\026.qdrant.DiscoverPoints\032\030.qdrant.D" +
      "iscoverResponse\"\000\022M\n\rDiscoverBatch\022\033.qdr" +
      "ant.DiscoverBatchPoints\032\035.qdrant.Discove" +
      "rBatchResponse\"\000\0225\n\005Count\022\023.qdrant.Count" +
      "Points\032\025.qdrant.CountResponse\"\000\022G\n\013Updat" +
      "eBatch\022\031.qdrant.UpdateBatchPoints\032\033.qdra" +
      "nt.UpdateBatchResponse\"\000\0225\n\005Query\022\023.qdra" +
      "nt.QueryPoints\032\025.qdrant.QueryResponse\"\000\022" +
      "D\n\nQueryBatch\022\030.qdrant.QueryBatchPoints\032" +
      "\032.qdrant.QueryBatchResponse\"\000\022F\n\013QueryGr" +
      "oups\022\030.qdrant.QueryPointGroups\032\033.qdrant." +
      "QueryGroupsResponse\"\000\0225\n\005Facet\022\023.qdrant." +
      "FacetCounts\032\025.qdrant.FacetResponse\"\000\022T\n\021" +
      "SearchMatrixPairs\022\032.qdrant.SearchMatrixP" +
      "oints\032!.qdrant.SearchMatrixPairsResponse" +
      "\"\000\022X\n\023SearchMatrixOffsets\022\032.qdrant.Searc" +
      "hMatrixPoints\032#.qdrant.SearchMatrixOffse" +
      "tsResponse\"\000B,\n\025io.qdrant.client.grpc\252\002\022" +
      "Qdrant.Client.Grpcb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.qdrant.client.grpc.Points.getDescriptor(),
        });
    io.qdrant.client.grpc.Points.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
