// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: qdrant_internal_service.proto

// Protobuf Java Version: 3.25.4
package io.qdrant.client.grpc;

public final class QdrantInternalService {
  private QdrantInternalService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetConsensusCommitRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:qdrant.GetConsensusCommitRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code qdrant.GetConsensusCommitRequest}
   */
  public static final class GetConsensusCommitRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:qdrant.GetConsensusCommitRequest)
      GetConsensusCommitRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetConsensusCommitRequest.newBuilder() to construct.
    private GetConsensusCommitRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetConsensusCommitRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetConsensusCommitRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.qdrant.client.grpc.QdrantInternalService.internal_static_qdrant_GetConsensusCommitRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.qdrant.client.grpc.QdrantInternalService.internal_static_qdrant_GetConsensusCommitRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitRequest.class, io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitRequest)) {
        return super.equals(obj);
      }
      io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitRequest other = (io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitRequest) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code qdrant.GetConsensusCommitRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:qdrant.GetConsensusCommitRequest)
        io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.qdrant.client.grpc.QdrantInternalService.internal_static_qdrant_GetConsensusCommitRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.qdrant.client.grpc.QdrantInternalService.internal_static_qdrant_GetConsensusCommitRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitRequest.class, io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitRequest.Builder.class);
      }

      // Construct using io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.qdrant.client.grpc.QdrantInternalService.internal_static_qdrant_GetConsensusCommitRequest_descriptor;
      }

      @java.lang.Override
      public io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitRequest getDefaultInstanceForType() {
        return io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitRequest.getDefaultInstance();
      }

      @java.lang.Override
      public io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitRequest build() {
        io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitRequest buildPartial() {
        io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitRequest result = new io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitRequest(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitRequest) {
          return mergeFrom((io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitRequest other) {
        if (other == io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:qdrant.GetConsensusCommitRequest)
    }

    // @@protoc_insertion_point(class_scope:qdrant.GetConsensusCommitRequest)
    private static final io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitRequest();
    }

    public static io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetConsensusCommitRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetConsensusCommitRequest>() {
      @java.lang.Override
      public GetConsensusCommitRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetConsensusCommitRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetConsensusCommitRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetConsensusCommitResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:qdrant.GetConsensusCommitResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Raft commit as u64
     * </pre>
     *
     * <code>int64 commit = 1;</code>
     * @return The commit.
     */
    long getCommit();

    /**
     * <pre>
     * Raft term as u64
     * </pre>
     *
     * <code>int64 term = 2;</code>
     * @return The term.
     */
    long getTerm();
  }
  /**
   * Protobuf type {@code qdrant.GetConsensusCommitResponse}
   */
  public static final class GetConsensusCommitResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:qdrant.GetConsensusCommitResponse)
      GetConsensusCommitResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetConsensusCommitResponse.newBuilder() to construct.
    private GetConsensusCommitResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetConsensusCommitResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetConsensusCommitResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.qdrant.client.grpc.QdrantInternalService.internal_static_qdrant_GetConsensusCommitResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.qdrant.client.grpc.QdrantInternalService.internal_static_qdrant_GetConsensusCommitResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitResponse.class, io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitResponse.Builder.class);
    }

    public static final int COMMIT_FIELD_NUMBER = 1;
    private long commit_ = 0L;
    /**
     * <pre>
     * Raft commit as u64
     * </pre>
     *
     * <code>int64 commit = 1;</code>
     * @return The commit.
     */
    @java.lang.Override
    public long getCommit() {
      return commit_;
    }

    public static final int TERM_FIELD_NUMBER = 2;
    private long term_ = 0L;
    /**
     * <pre>
     * Raft term as u64
     * </pre>
     *
     * <code>int64 term = 2;</code>
     * @return The term.
     */
    @java.lang.Override
    public long getTerm() {
      return term_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (commit_ != 0L) {
        output.writeInt64(1, commit_);
      }
      if (term_ != 0L) {
        output.writeInt64(2, term_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (commit_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, commit_);
      }
      if (term_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, term_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitResponse)) {
        return super.equals(obj);
      }
      io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitResponse other = (io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitResponse) obj;

      if (getCommit()
          != other.getCommit()) return false;
      if (getTerm()
          != other.getTerm()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COMMIT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCommit());
      hash = (37 * hash) + TERM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTerm());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code qdrant.GetConsensusCommitResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:qdrant.GetConsensusCommitResponse)
        io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.qdrant.client.grpc.QdrantInternalService.internal_static_qdrant_GetConsensusCommitResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.qdrant.client.grpc.QdrantInternalService.internal_static_qdrant_GetConsensusCommitResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitResponse.class, io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitResponse.Builder.class);
      }

      // Construct using io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        commit_ = 0L;
        term_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.qdrant.client.grpc.QdrantInternalService.internal_static_qdrant_GetConsensusCommitResponse_descriptor;
      }

      @java.lang.Override
      public io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitResponse getDefaultInstanceForType() {
        return io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitResponse.getDefaultInstance();
      }

      @java.lang.Override
      public io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitResponse build() {
        io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitResponse buildPartial() {
        io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitResponse result = new io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.commit_ = commit_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.term_ = term_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitResponse) {
          return mergeFrom((io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitResponse other) {
        if (other == io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitResponse.getDefaultInstance()) return this;
        if (other.getCommit() != 0L) {
          setCommit(other.getCommit());
        }
        if (other.getTerm() != 0L) {
          setTerm(other.getTerm());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                commit_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                term_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long commit_ ;
      /**
       * <pre>
       * Raft commit as u64
       * </pre>
       *
       * <code>int64 commit = 1;</code>
       * @return The commit.
       */
      @java.lang.Override
      public long getCommit() {
        return commit_;
      }
      /**
       * <pre>
       * Raft commit as u64
       * </pre>
       *
       * <code>int64 commit = 1;</code>
       * @param value The commit to set.
       * @return This builder for chaining.
       */
      public Builder setCommit(long value) {

        commit_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Raft commit as u64
       * </pre>
       *
       * <code>int64 commit = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCommit() {
        bitField0_ = (bitField0_ & ~0x00000001);
        commit_ = 0L;
        onChanged();
        return this;
      }

      private long term_ ;
      /**
       * <pre>
       * Raft term as u64
       * </pre>
       *
       * <code>int64 term = 2;</code>
       * @return The term.
       */
      @java.lang.Override
      public long getTerm() {
        return term_;
      }
      /**
       * <pre>
       * Raft term as u64
       * </pre>
       *
       * <code>int64 term = 2;</code>
       * @param value The term to set.
       * @return This builder for chaining.
       */
      public Builder setTerm(long value) {

        term_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Raft term as u64
       * </pre>
       *
       * <code>int64 term = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTerm() {
        bitField0_ = (bitField0_ & ~0x00000002);
        term_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:qdrant.GetConsensusCommitResponse)
    }

    // @@protoc_insertion_point(class_scope:qdrant.GetConsensusCommitResponse)
    private static final io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitResponse();
    }

    public static io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetConsensusCommitResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetConsensusCommitResponse>() {
      @java.lang.Override
      public GetConsensusCommitResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetConsensusCommitResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetConsensusCommitResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.qdrant.client.grpc.QdrantInternalService.GetConsensusCommitResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WaitOnConsensusCommitRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:qdrant.WaitOnConsensusCommitRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Raft commit as u64
     * </pre>
     *
     * <code>int64 commit = 1;</code>
     * @return The commit.
     */
    long getCommit();

    /**
     * <pre>
     * Raft term as u64
     * </pre>
     *
     * <code>int64 term = 2;</code>
     * @return The term.
     */
    long getTerm();

    /**
     * <pre>
     * Timeout in seconds
     * </pre>
     *
     * <code>int64 timeout = 3;</code>
     * @return The timeout.
     */
    long getTimeout();
  }
  /**
   * Protobuf type {@code qdrant.WaitOnConsensusCommitRequest}
   */
  public static final class WaitOnConsensusCommitRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:qdrant.WaitOnConsensusCommitRequest)
      WaitOnConsensusCommitRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WaitOnConsensusCommitRequest.newBuilder() to construct.
    private WaitOnConsensusCommitRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WaitOnConsensusCommitRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new WaitOnConsensusCommitRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.qdrant.client.grpc.QdrantInternalService.internal_static_qdrant_WaitOnConsensusCommitRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.qdrant.client.grpc.QdrantInternalService.internal_static_qdrant_WaitOnConsensusCommitRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitRequest.class, io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitRequest.Builder.class);
    }

    public static final int COMMIT_FIELD_NUMBER = 1;
    private long commit_ = 0L;
    /**
     * <pre>
     * Raft commit as u64
     * </pre>
     *
     * <code>int64 commit = 1;</code>
     * @return The commit.
     */
    @java.lang.Override
    public long getCommit() {
      return commit_;
    }

    public static final int TERM_FIELD_NUMBER = 2;
    private long term_ = 0L;
    /**
     * <pre>
     * Raft term as u64
     * </pre>
     *
     * <code>int64 term = 2;</code>
     * @return The term.
     */
    @java.lang.Override
    public long getTerm() {
      return term_;
    }

    public static final int TIMEOUT_FIELD_NUMBER = 3;
    private long timeout_ = 0L;
    /**
     * <pre>
     * Timeout in seconds
     * </pre>
     *
     * <code>int64 timeout = 3;</code>
     * @return The timeout.
     */
    @java.lang.Override
    public long getTimeout() {
      return timeout_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (commit_ != 0L) {
        output.writeInt64(1, commit_);
      }
      if (term_ != 0L) {
        output.writeInt64(2, term_);
      }
      if (timeout_ != 0L) {
        output.writeInt64(3, timeout_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (commit_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, commit_);
      }
      if (term_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, term_);
      }
      if (timeout_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timeout_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitRequest)) {
        return super.equals(obj);
      }
      io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitRequest other = (io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitRequest) obj;

      if (getCommit()
          != other.getCommit()) return false;
      if (getTerm()
          != other.getTerm()) return false;
      if (getTimeout()
          != other.getTimeout()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COMMIT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCommit());
      hash = (37 * hash) + TERM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTerm());
      hash = (37 * hash) + TIMEOUT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimeout());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code qdrant.WaitOnConsensusCommitRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:qdrant.WaitOnConsensusCommitRequest)
        io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.qdrant.client.grpc.QdrantInternalService.internal_static_qdrant_WaitOnConsensusCommitRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.qdrant.client.grpc.QdrantInternalService.internal_static_qdrant_WaitOnConsensusCommitRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitRequest.class, io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitRequest.Builder.class);
      }

      // Construct using io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        commit_ = 0L;
        term_ = 0L;
        timeout_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.qdrant.client.grpc.QdrantInternalService.internal_static_qdrant_WaitOnConsensusCommitRequest_descriptor;
      }

      @java.lang.Override
      public io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitRequest getDefaultInstanceForType() {
        return io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitRequest.getDefaultInstance();
      }

      @java.lang.Override
      public io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitRequest build() {
        io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitRequest buildPartial() {
        io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitRequest result = new io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.commit_ = commit_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.term_ = term_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.timeout_ = timeout_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitRequest) {
          return mergeFrom((io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitRequest other) {
        if (other == io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitRequest.getDefaultInstance()) return this;
        if (other.getCommit() != 0L) {
          setCommit(other.getCommit());
        }
        if (other.getTerm() != 0L) {
          setTerm(other.getTerm());
        }
        if (other.getTimeout() != 0L) {
          setTimeout(other.getTimeout());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                commit_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                term_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                timeout_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long commit_ ;
      /**
       * <pre>
       * Raft commit as u64
       * </pre>
       *
       * <code>int64 commit = 1;</code>
       * @return The commit.
       */
      @java.lang.Override
      public long getCommit() {
        return commit_;
      }
      /**
       * <pre>
       * Raft commit as u64
       * </pre>
       *
       * <code>int64 commit = 1;</code>
       * @param value The commit to set.
       * @return This builder for chaining.
       */
      public Builder setCommit(long value) {

        commit_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Raft commit as u64
       * </pre>
       *
       * <code>int64 commit = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCommit() {
        bitField0_ = (bitField0_ & ~0x00000001);
        commit_ = 0L;
        onChanged();
        return this;
      }

      private long term_ ;
      /**
       * <pre>
       * Raft term as u64
       * </pre>
       *
       * <code>int64 term = 2;</code>
       * @return The term.
       */
      @java.lang.Override
      public long getTerm() {
        return term_;
      }
      /**
       * <pre>
       * Raft term as u64
       * </pre>
       *
       * <code>int64 term = 2;</code>
       * @param value The term to set.
       * @return This builder for chaining.
       */
      public Builder setTerm(long value) {

        term_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Raft term as u64
       * </pre>
       *
       * <code>int64 term = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTerm() {
        bitField0_ = (bitField0_ & ~0x00000002);
        term_ = 0L;
        onChanged();
        return this;
      }

      private long timeout_ ;
      /**
       * <pre>
       * Timeout in seconds
       * </pre>
       *
       * <code>int64 timeout = 3;</code>
       * @return The timeout.
       */
      @java.lang.Override
      public long getTimeout() {
        return timeout_;
      }
      /**
       * <pre>
       * Timeout in seconds
       * </pre>
       *
       * <code>int64 timeout = 3;</code>
       * @param value The timeout to set.
       * @return This builder for chaining.
       */
      public Builder setTimeout(long value) {

        timeout_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Timeout in seconds
       * </pre>
       *
       * <code>int64 timeout = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimeout() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timeout_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:qdrant.WaitOnConsensusCommitRequest)
    }

    // @@protoc_insertion_point(class_scope:qdrant.WaitOnConsensusCommitRequest)
    private static final io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitRequest();
    }

    public static io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WaitOnConsensusCommitRequest>
        PARSER = new com.google.protobuf.AbstractParser<WaitOnConsensusCommitRequest>() {
      @java.lang.Override
      public WaitOnConsensusCommitRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<WaitOnConsensusCommitRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WaitOnConsensusCommitRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WaitOnConsensusCommitResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:qdrant.WaitOnConsensusCommitResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * False if commit/term is diverged and never reached or if timed out.
     * </pre>
     *
     * <code>bool ok = 1;</code>
     * @return The ok.
     */
    boolean getOk();
  }
  /**
   * Protobuf type {@code qdrant.WaitOnConsensusCommitResponse}
   */
  public static final class WaitOnConsensusCommitResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:qdrant.WaitOnConsensusCommitResponse)
      WaitOnConsensusCommitResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WaitOnConsensusCommitResponse.newBuilder() to construct.
    private WaitOnConsensusCommitResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WaitOnConsensusCommitResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new WaitOnConsensusCommitResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.qdrant.client.grpc.QdrantInternalService.internal_static_qdrant_WaitOnConsensusCommitResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.qdrant.client.grpc.QdrantInternalService.internal_static_qdrant_WaitOnConsensusCommitResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitResponse.class, io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitResponse.Builder.class);
    }

    public static final int OK_FIELD_NUMBER = 1;
    private boolean ok_ = false;
    /**
     * <pre>
     * False if commit/term is diverged and never reached or if timed out.
     * </pre>
     *
     * <code>bool ok = 1;</code>
     * @return The ok.
     */
    @java.lang.Override
    public boolean getOk() {
      return ok_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (ok_ != false) {
        output.writeBool(1, ok_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (ok_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, ok_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitResponse)) {
        return super.equals(obj);
      }
      io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitResponse other = (io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitResponse) obj;

      if (getOk()
          != other.getOk()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getOk());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code qdrant.WaitOnConsensusCommitResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:qdrant.WaitOnConsensusCommitResponse)
        io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.qdrant.client.grpc.QdrantInternalService.internal_static_qdrant_WaitOnConsensusCommitResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.qdrant.client.grpc.QdrantInternalService.internal_static_qdrant_WaitOnConsensusCommitResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitResponse.class, io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitResponse.Builder.class);
      }

      // Construct using io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        ok_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.qdrant.client.grpc.QdrantInternalService.internal_static_qdrant_WaitOnConsensusCommitResponse_descriptor;
      }

      @java.lang.Override
      public io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitResponse getDefaultInstanceForType() {
        return io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitResponse.getDefaultInstance();
      }

      @java.lang.Override
      public io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitResponse build() {
        io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitResponse buildPartial() {
        io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitResponse result = new io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.ok_ = ok_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitResponse) {
          return mergeFrom((io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitResponse other) {
        if (other == io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitResponse.getDefaultInstance()) return this;
        if (other.getOk() != false) {
          setOk(other.getOk());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                ok_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean ok_ ;
      /**
       * <pre>
       * False if commit/term is diverged and never reached or if timed out.
       * </pre>
       *
       * <code>bool ok = 1;</code>
       * @return The ok.
       */
      @java.lang.Override
      public boolean getOk() {
        return ok_;
      }
      /**
       * <pre>
       * False if commit/term is diverged and never reached or if timed out.
       * </pre>
       *
       * <code>bool ok = 1;</code>
       * @param value The ok to set.
       * @return This builder for chaining.
       */
      public Builder setOk(boolean value) {

        ok_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * False if commit/term is diverged and never reached or if timed out.
       * </pre>
       *
       * <code>bool ok = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOk() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ok_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:qdrant.WaitOnConsensusCommitResponse)
    }

    // @@protoc_insertion_point(class_scope:qdrant.WaitOnConsensusCommitResponse)
    private static final io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitResponse();
    }

    public static io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WaitOnConsensusCommitResponse>
        PARSER = new com.google.protobuf.AbstractParser<WaitOnConsensusCommitResponse>() {
      @java.lang.Override
      public WaitOnConsensusCommitResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<WaitOnConsensusCommitResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WaitOnConsensusCommitResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.qdrant.client.grpc.QdrantInternalService.WaitOnConsensusCommitResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_qdrant_GetConsensusCommitRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_qdrant_GetConsensusCommitRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_qdrant_GetConsensusCommitResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_qdrant_GetConsensusCommitResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_qdrant_WaitOnConsensusCommitRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_qdrant_WaitOnConsensusCommitRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_qdrant_WaitOnConsensusCommitResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_qdrant_WaitOnConsensusCommitResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035qdrant_internal_service.proto\022\006qdrant\"" +
      "\033\n\031GetConsensusCommitRequest\":\n\032GetConse" +
      "nsusCommitResponse\022\016\n\006commit\030\001 \001(\003\022\014\n\004te" +
      "rm\030\002 \001(\003\"M\n\034WaitOnConsensusCommitRequest" +
      "\022\016\n\006commit\030\001 \001(\003\022\014\n\004term\030\002 \001(\003\022\017\n\007timeou" +
      "t\030\003 \001(\003\"+\n\035WaitOnConsensusCommitResponse" +
      "\022\n\n\002ok\030\001 \001(\0102\327\001\n\016QdrantInternal\022]\n\022GetCo" +
      "nsensusCommit\022!.qdrant.GetConsensusCommi" +
      "tRequest\032\".qdrant.GetConsensusCommitResp" +
      "onse\"\000\022f\n\025WaitOnConsensusCommit\022$.qdrant" +
      ".WaitOnConsensusCommitRequest\032%.qdrant.W" +
      "aitOnConsensusCommitResponse\"\000B,\n\025io.qdr" +
      "ant.client.grpc\252\002\022Qdrant.Client.Grpcb\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_qdrant_GetConsensusCommitRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_qdrant_GetConsensusCommitRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_qdrant_GetConsensusCommitRequest_descriptor,
        new java.lang.String[] { });
    internal_static_qdrant_GetConsensusCommitResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_qdrant_GetConsensusCommitResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_qdrant_GetConsensusCommitResponse_descriptor,
        new java.lang.String[] { "Commit", "Term", });
    internal_static_qdrant_WaitOnConsensusCommitRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_qdrant_WaitOnConsensusCommitRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_qdrant_WaitOnConsensusCommitRequest_descriptor,
        new java.lang.String[] { "Commit", "Term", "Timeout", });
    internal_static_qdrant_WaitOnConsensusCommitResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_qdrant_WaitOnConsensusCommitResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_qdrant_WaitOnConsensusCommitResponse_descriptor,
        new java.lang.String[] { "Ok", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
